DEMCODE_TO_ENG = {
 2011: 'Male gender',
 2012: 'Female gender',
 2013: 'Gender diverse',
 2014: 'Indigenous ',
 2015: 'Non-Indigenous ',
 2016: 'First Nation (North American Indian)',
 2017: 'Métis',
 2018: 'Inuk (Inuit)',
 2019: 'Person with a disability',
 2020: 'Not a person with a disability',
 2021: 'A seeing disability affects vision, including total blindness, partial sight and visual distortion',
 2022: 'A seeing disability affects vision, including total blindness, partial sight and visual distortion - Not selected',
 2023: 'A hearing disability affects ability to hear, including being hard of hearing, deafness or acoustic distortion',
 2024: 'A hearing disability affects ability to hear, including being hard of hearing, deafness or acoustic distortion - Not selected',
 2025: 'A mobility issue affects ability to move your body, including the required use of a wheelchair or a cane, or other issues impacting your mobility',
 2026: 'A mobility issue affects ability to move your body, including the required use of a wheelchair or a cane, or other issues impacting your mobility - Not selected',
 2027: 'An issue with flexibility or dexterity affects ability to move joints or perform motor tasks, especially with your hands',
 2028: 'An issue with flexibility or dexterity affects ability to move joints or perform motor tasks, especially with your hands - Not selected',
 2029: 'A mental health issue affects psychology or behaviour, such as anxiety, depression or social / compulsive disorder or phobia or psychiatric illness',
 2030: 'A mental health issue affects psychology or behaviour, such as anxiety, depression or social / compulsive disorder or phobia or psychiatric illness - Not selected',
 2031: 'A sensory / environmental disability affects sensitivity to light, sounds or other distractions, as well as allergens and other environmental sensitivities',
 2032: 'A sensory / environmental disability affects sensitivity to light, sounds or other distractions, as well as allergens and other environmental sensitivities - Not selected',
 2033: 'A chronic health condition or pain affects ability to function on a regular or episodic basis due to migraines, Crohn’s disease, colitis, and other disabilities or health conditions',
 2034: 'A chronic health condition or pain affects ability to function on a regular or episodic basis due to migraines, Crohn’s disease, colitis, and other disabilities or health conditions - Not selected',
 2035: 'A cognitive disability affects ability to carry out tasks involving executive functioning, such as planning and organization, learning information, communication and memory, including autism or Asperger’s syndrome, attention deficit disorder, and learning disabilities',
 2036: 'A cognitive disability affects ability to carry out tasks involving executive functioning, such as planning and organization, learning information, communication and memory, including autism or Asperger’s syndrome, attention deficit disorder, and learning  disabilities - Not selected',
 2037: 'An intellectual disability affects your ability to learn and to adapt behaviour to different situations',
 2038: 'An intellectual disability affects your ability to learn and to adapt behaviour to different situations - Not selected',
 2039: 'Other disability (including: learning disabilities, developmental disabilities and all other types of disabilities)',
 2040: 'Other disability (including: learning disabilities, developmental disabilities and all other types of disabilities) - Not selected',
 2041: 'Visible minority',
 2042: 'Non-visible minority',
 2043: 'Black',
 2044: 'Black - Not selected',
 2045: 'Chinese',
 2046: 'Chinese - Not selected',
 2047: 'Filipino',
 2048: 'Filipino - Not selected',
 2049: 'Japanese',
 2050: 'Japanese - Not selected',
 2051: 'Korean',
 2052: 'Korean - Not selected',
 2053: 'South Asian/East Indian (including: Indian from India; Bangladeshi; Pakistani; East Indian from Guyana, Trinidad, East Africa; etc.)',
 2054: 'South Asian/East Indian (including: Indian from India; Bangladeshi; Pakistani; East Indian from Guyana, Trinidad, East Africa; etc.) - Not selected',
 2055: 'Southeast Asian (including: Burmese; Cambodian; Laotian; Thai; Vietnamese; etc.)',
 2056: 'Southeast Asian (including: Burmese; Cambodian; Laotian; Thai; Vietnamese; etc.) - Not selected',
 2057: 'Non-White West Asian, North African or Arab (including: Egyptian; Libyan; Lebanese; Iranian; etc.)',
 2058: 'Non-White West Asian, North African or Arab (including: Egyptian; Libyan; Lebanese; Iranian; etc.) - Not selected',
 2059: 'Non-White Latin American (including: Indigenous persons from Central and South America, etc.)',
 2060: 'Non-White Latin American (including: Indigenous persons from Central and South America, etc.) - Not selected',
 2061: 'Person of mixed origin (with one parent in one of the visible minority groups)',
 2062: 'Person of mixed origin (with one parent in one of the visible minority groups) - Not selected',
 2063: 'Other visible minority group',
 2064: 'Other visible minority group - Not selected',
 2065: 'Heterosexual',
 2066: 'Gay/lesbian',
 2067: 'Bisexual',
 2068: 'Other',
 2069: 'No answer'
}